FROM node:10

RUN apt-get update
RUN apt-get install -y netcat
RUN apt-get clean

WORKDIR /contracts

COPY ./package.json .
COPY ./contracts/package.json ./contracts/
COPY ./deploy/package.json ./deploy/
COPY ./upgrade/package.json ./upgrade/
COPY ./yarn.lock .

RUN yarn install --frozen-lockfile

COPY ./contracts/truffle-config.js ./contracts/truffle-config.js
COPY ./contracts ./contracts

RUN yarn build

COPY .eslintignore .eslintignore
COPY .eslintrc .eslintrc
COPY .prettierrc .prettierrc

COPY ./upgrade ./upgrade
COPY deploy.sh deploy.sh
COPY ./deploy ./deploy
COPY .solhint.json .solhint.json
COPY codechecks.yml codechecks.yml

ENV PATH="/contracts/:${PATH}"
ENV NOFLAT=true
