const MessageTest = artifacts.require("MessageTest.sol");

contract('ArbitraryMessage.sol', async () => {
  describe('unpackData', () => {
    it('unpack dataType 0x00', async () => {
      // given
      const sender = '0x003667154bb32e42bb9e1e6532f19d187fa0082e'
      const contractAddress = '0xf4bef13f9f4f2b203faf0c3cbbaabe1afe056955'
      const txHash = '0xbdceda9d8c94838aca10c687da1411a07b1390e88239c0638cb9cc264219cc10'
      const gasLimit = '1535604485'
      const gasPrice = '0'
      const dataType = '0x00'
      const data = '0xb1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03'
      // event message generated by
      // requireToPassMessage(address _contract, bytes _data, uint256 _gas)
      const eventMessage = "0x003667154bb32e42bb9e1e6532f19d187fa0082e" + // sender
        "f4bef13f9f4f2b203faf0c3cbbaabe1afe056955" + // contractAddress
        "000000000000000000000000000000000000000000000000000000005b877705" + // gasLimit
        "00" + // dataType
        "b1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03" // data

      // validator needs to add txHash into message
      const message = eventMessage.slice(0, 82) + txHash.replace(/^0x/, '') + eventMessage.slice(82)

      // when
      const messageTest = await MessageTest.new()
      const result = await messageTest.unpackData(message)

      // then
      expect(result.length).to.be.equal(7)
      const [_sender, _executor, _txHash, _gasLimit, _dataType, _gasPrice, _data] = result
      expect(_sender).to.be.equal(sender)
      expect(_executor).to.be.equal(contractAddress)
      expect(_txHash).to.be.equal(txHash)
      expect(_gasLimit.toString()).to.be.equal(gasLimit)
      expect(_dataType).to.be.equal(dataType)
      expect(_gasPrice.toString()).to.be.equal(gasPrice)
      expect(_data).to.be.equal(data)
    })

    it('unpack dataType 0x01', async () => {
      // given
      const sender = '0xc95e32f5b21aea8107aa2c645636e909489031e8'
      const contractAddress = '0xf4bef13f9f4f2b203faf0c3cbbaabe1afe056955'
      const txHash = '0x27aa676e59e4feaafcfde2b88c6002b756795c1260762512ba26ff28fdaf0f64'
      const gasLimit = '1535604485'
      const gasPrice = '6000000000'
      const dataType = '0x01'
      const data = '0xb1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03'
      // event message generated by
      // requireToPassMessage(address _contract, bytes _data, uint256 _gas, uint256 _gasPrice)
      const eventMessage = "0xc95e32f5b21aea8107aa2c645636e909489031e8" + // sender
        "f4bef13f9f4f2b203faf0c3cbbaabe1afe056955" + // contractAddress
        "000000000000000000000000000000000000000000000000000000005b877705" + // gasLimit
        "01" + // dataType
        "0000000000000000000000000000000000000000000000000000000165a0bc00" + // gasPrice
        "b1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03" // data

      // validator needs to add txHash into message
      const message = eventMessage.slice(0, 82) + txHash.replace(/^0x/, '') + eventMessage.slice(82)

      // when
      const messageTest = await MessageTest.new()
      const result = await messageTest.unpackData(message)

      // then
      expect(result.length).to.be.equal(7)
      const [_sender, _executor, _txHash, _gasLimit, _dataType, _gasPrice, _data] = result
      expect(_sender).to.be.equal(sender)
      expect(_executor).to.be.equal(contractAddress)
      expect(_txHash).to.be.equal(txHash)
      expect(_gasLimit.toString()).to.be.equal(gasLimit)
      expect(_dataType).to.be.equal(dataType)
      expect(_gasPrice.toString()).to.be.equal(gasPrice)
      expect(_data).to.be.equal(data)
    })

    it('unpack dataType 0x02', async () => {
      // given
      const sender = '0xe0241f385c58c88911531ddfe3b5f0fc729bdaee'
      const contractAddress = '0xf4bef13f9f4f2b203faf0c3cbbaabe1afe056955'
      const txHash = '0xbdceda9d8c94838aca10c687da1411a07b1390e88239c0638cb9cc264219cc10'
      const gasLimit = '1535604485'
      const gasPrice = '0'
      const dataType = '0x02'
      const data = '0xb1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03'
      // event message generated by
      // requireToPassMessage(address _contract, bytes _data, uint256 _gas, bytes1 _oracleGasPriceSpeed)
      const eventMessage = "0xe0241f385c58c88911531ddfe3b5f0fc729bdaee" + // sender
        "f4bef13f9f4f2b203faf0c3cbbaabe1afe056955" + // contractAddress
        "000000000000000000000000000000000000000000000000000000005b877705" + // gasLimit
        "02" + // dataType
        "10b1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03" // data

      // validator needs to add txHash into message
      const message = eventMessage.slice(0, 82) + txHash.replace(/^0x/, '') + eventMessage.slice(82)

      // when
      const messageTest = await MessageTest.new()
      const result = await messageTest.unpackData(message)

      // then
      expect(result.length).to.be.equal(7)
      const [_sender, _executor, _txHash, _gasLimit, _dataType, _gasPrice, _data] = result
      expect(_sender).to.be.equal(sender)
      expect(_executor).to.be.equal(contractAddress)
      expect(_txHash).to.be.equal(txHash)
      expect(_gasLimit.toString()).to.be.equal(gasLimit)
      expect(_dataType).to.be.equal(dataType)
      expect(_gasPrice.toString()).to.be.equal(gasPrice)
      expect(_data).to.be.equal(data)
    })
  })
  describe('unpackData with signatures parameters', () => {
    let v, r, s
    before(async () => {
      v = [ 28 ]
      r = [ '0xdbc46dc3166efb080c8af49df3fffb96547849cd029ed9576b74f859b5e9d17b' ]
      s = [ '0x367c67e056f6f9d676cb455e924457be2ac349a13cb1b46d5bc2ca99c1f3918f' ]
    })
    it('unpack dataType 0x00', async () => {
      // given
      const sender = '0x003667154bb32e42bb9e1e6532f19d187fa0082e'
      const contractAddress = '0xf4bef13f9f4f2b203faf0c3cbbaabe1afe056955'
      const txHash = '0xbdceda9d8c94838aca10c687da1411a07b1390e88239c0638cb9cc264219cc10'
      const gasLimit = '1535604485'
      const gasPrice = '0'
      const dataType = '0x00'
      const data = '0xb1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03'
      // event message generated by
      // requireToPassMessage(address _contract, bytes _data, uint256 _gas)
      const eventMessage = "0x003667154bb32e42bb9e1e6532f19d187fa0082e" + // sender
        "f4bef13f9f4f2b203faf0c3cbbaabe1afe056955" + // contractAddress
        "000000000000000000000000000000000000000000000000000000005b877705" + // gasLimit
        "00" + // dataType
        "b1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03" // data

      // validator needs to add txHash into message
      const message = eventMessage.slice(0, 82) + txHash.replace(/^0x/, '') + eventMessage.slice(82)

      // when
      const messageTest = await MessageTest.new()
      const result = await messageTest.unpackDataWithExtraParams(message, [v], [r], [s])

      // then
      expect(result.length).to.be.equal(7)
      const [_sender, _executor, _txHash, _gasLimit, _dataType, _gasPrice, _data] = result
      expect(_sender).to.be.equal(sender)
      expect(_executor).to.be.equal(contractAddress)
      expect(_txHash).to.be.equal(txHash)
      expect(_gasLimit.toString()).to.be.equal(gasLimit)
      expect(_dataType).to.be.equal(dataType)
      expect(_gasPrice.toString()).to.be.equal(gasPrice)
      expect(_data).to.be.equal(data)
    })

    it('unpack dataType 0x01', async () => {
      // given
      const sender = '0xc95e32f5b21aea8107aa2c645636e909489031e8'
      const contractAddress = '0xf4bef13f9f4f2b203faf0c3cbbaabe1afe056955'
      const txHash = '0x27aa676e59e4feaafcfde2b88c6002b756795c1260762512ba26ff28fdaf0f64'
      const gasLimit = '1535604485'
      const gasPrice = '6000000000'
      const dataType = '0x01'
      const data = '0xb1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03'
      // event message generated by
      // requireToPassMessage(address _contract, bytes _data, uint256 _gas, uint256 _gasPrice)
      const eventMessage = "0xc95e32f5b21aea8107aa2c645636e909489031e8" + // sender
        "f4bef13f9f4f2b203faf0c3cbbaabe1afe056955" + // contractAddress
        "000000000000000000000000000000000000000000000000000000005b877705" + // gasLimit
        "01" + // dataType
        "0000000000000000000000000000000000000000000000000000000165a0bc00" + // gasPrice
        "b1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03" // data

      // validator needs to add txHash into message
      const message = eventMessage.slice(0, 82) + txHash.replace(/^0x/, '') + eventMessage.slice(82)

      // when
      const messageTest = await MessageTest.new()
      const result = await messageTest.unpackDataWithExtraParams(message, [v], [r], [s])

      // then
      expect(result.length).to.be.equal(7)
      const [_sender, _executor, _txHash, _gasLimit, _dataType, _gasPrice, _data] = result
      expect(_sender).to.be.equal(sender)
      expect(_executor).to.be.equal(contractAddress)
      expect(_txHash).to.be.equal(txHash)
      expect(_gasLimit.toString()).to.be.equal(gasLimit)
      expect(_dataType).to.be.equal(dataType)
      expect(_gasPrice.toString()).to.be.equal(gasPrice)
      expect(_data).to.be.equal(data)
    })

    it('unpack dataType 0x02', async () => {
      // given
      const sender = '0xe0241f385c58c88911531ddfe3b5f0fc729bdaee'
      const contractAddress = '0xf4bef13f9f4f2b203faf0c3cbbaabe1afe056955'
      const txHash = '0xbdceda9d8c94838aca10c687da1411a07b1390e88239c0638cb9cc264219cc10'
      const gasLimit = '1535604485'
      const gasPrice = '0'
      const dataType = '0x02'
      const data = '0xb1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03'
      // event message generated by
      // requireToPassMessage(address _contract, bytes _data, uint256 _gas, bytes1 _oracleGasPriceSpeed)
      const eventMessage = "0xe0241f385c58c88911531ddfe3b5f0fc729bdaee" + // sender
        "f4bef13f9f4f2b203faf0c3cbbaabe1afe056955" + // contractAddress
        "000000000000000000000000000000000000000000000000000000005b877705" + // gasLimit
        "02" + // dataType
        "10b1591967aed668a4b27645ff40c444892d91bf5951b382995d4d4f6ee3a2ce03" // data

      // validator needs to add txHash into message
      const message = eventMessage.slice(0, 82) + txHash.replace(/^0x/, '') + eventMessage.slice(82)

      // when
      const messageTest = await MessageTest.new()
      const result = await messageTest.unpackDataWithExtraParams(message, [v], [r], [s])

      // then
      expect(result.length).to.be.equal(7)
      const [_sender, _executor, _txHash, _gasLimit, _dataType, _gasPrice, _data] = result
      expect(_sender).to.be.equal(sender)
      expect(_executor).to.be.equal(contractAddress)
      expect(_txHash).to.be.equal(txHash)
      expect(_gasLimit.toString()).to.be.equal(gasLimit)
      expect(_dataType).to.be.equal(dataType)
      expect(_gasPrice.toString()).to.be.equal(gasPrice)
      expect(_data).to.be.equal(data)
    })
  })
})
